### ISSUE TITLE
Spells won't load

### ISSUE THREAD

**Issue by tankorsmash** [larzm42/dom5inspector#1]
Going to https://larzm42.github.io/dom5inspector/? and trying to load a spell. I don't see any spells listed without pressing anything, and adding in a search query doesn't seem ot help much.

Not sure if I can add much to this, but here's an error that has appeared on page load.

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at updateIdxById (slick.dataview.js:102)
    at DataView.setItems (slick.dataview.js:131)
    at Object.init (CGrid.js?v=30:446)
    at MSpell.js?v=30:644
```

where the line is

          for (var i = startingIndex, l = items.length; i < l; i++)

Looking quickly through the code, it seems like `gamedata/spells.csv` is missing, so maybe the data hasn't been pulled out of D5 yet and you're way ahead of me.

**Comment by larzm42** [comment]
The spell data is now included.
