### ISSUE TITLE
Recruitment points are showing 10000 for all units

### ISSUE THREAD

**Issue by TomBowden2019** [larzm42/dom5inspector#26]
![Screen Shot 2020-05-01 at 8 54 39 AM](https://user-images.githubusercontent.com/57361527/80810510-9d0ee180-8b89-11ea-831c-e5743136f0e4.png)

Tom

**Comment by larzm42** [comment]
Working as intended. I don't know the recruitment point formula so displaying the raw value. See:
http://illwinter.com/dom5/modmanual.html#gold-resource-cost
