### ISSUE TITLE
Include pretender chassis data

### ISSUE THREAD

**Issue by jeeger** [larzm42/dom5inspector#3]
First off, thanks for this wonderful (and well designed!) piece of software. I do however have an improvement to suggest: I don't know how much work it would be, but would it be possible to add all pretender chassis' to the unit data?

AFAIK, there's really no way of looking at all available chassis' without going into the game, and this would fit the gap nicely.

**Comment by larzm42** [comment]
You can view all pretenders by choosing pretender in the unit type drop down. https://larzm42.github.io/dom5inspector/?page=unit&unittype=8 

You can filter by nation by choosing a nation in drop down as well.

**Comment by jeeger** [comment]
Oh wow, I had hoped for something like this. Cool! 

On January 6, 2018 2:32:53 AM GMT+01:00, larzm42 <notifications@github.com> wrote:
>You can view all pretenders by choosing pretender in the unit type drop
>down. https://larzm42.github.io/dom5inspector/?page=unit&unittype=8 
>
>You can filter by nation by choosing a nation in drop down as well.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/larzm42/dom5inspector/issues/3#issuecomment-355712651

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
