### ISSUE TITLE
Event has an "unknown" which I know

### ISSUE THREAD

**Issue by qwertystop** [larzm42/dom5inspector#5]
Event 2385 ("One of your mages has consorted with a witch in the woods..." is listed in the inspector as causing an unknown affliction. I got it; the affliction is called Tainted Presence. It says it provides increased magic leadership, but the fluff-text implies that it might also trigger Horror-related events. I don't know whether that'll pan out to anything. If nothing else, you should be able to fill in the name now for that event and anything else that causes it.

**Comment by larzm42** [comment]
Added the affliction.
